[build]
builder = "nixpacks"

[deploy]
startCommand = "deno run --allow-net --allow-read --allow-write --allow-env --allow-ffi deno-backend/main.ts"
healthcheckPath = "/api/health.php"
healthcheckTimeout = 10
